[package]
name = "e_drone_rpi"
version = "0.1.0"
authors = ["Sanghyo Lee"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "E-DRONE rust library for Raspberry PI."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
